force-app/main/default/objects/Opportunity_Calculator_Based_On_Role__mdt/Opportunity_Calculator_Based_On_Role__mdt.object-meta.xml
<CustomObject>
    <description>Developer&apos;s name should be exactly the same like developer name of the role</description>
    <label>Opportunity Calculator Based On Role</label>
    <pluralLabel>Opportunity Calculator Based On Role</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity_Calculator_Based_On_Role__mdt/fields/Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Max_Discount__c</fullName>
    <label>Max Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/OppCalculatorManager_Service.cls
/**
 * The OppCalculatorManager_Service class implements the OppCalculator_Interface to calculate opportunities
 * based on the role of the opportunity owner being Manager.
 * It sets the maximum discount for each opportunity based on the configured setting for the Manager role.
 *
 * @author Piotr Rodak
 * @date March 2024
 */
public with sharing class OppCalculatorManager_Service implements OppCalculator_Interface {

    /**
     * The setting for the Manager role, obtained from Custom Metadata Type Opportunity_Calculator_Based_On_Role__mdt.
     */
    private Opportunity_Calculator_Based_On_Role__mdt roleSetting;

    /**
     * Constructs a new OppCalculatorManager_Service instance.
     * Initializes the roleSetting variable by retrieving the configuration for the Manager role from Custom Metadata.
     */
    public OppCalculatorManager_Service() {
        roleSetting = Opportunity_Calculator_Based_On_Role__mdt.getInstance('Manager');
    }

    /**
     * Calculates opportunities based on the configured setting for the Manager role.
     * Sets the maximum discount for each opportunity to the value specified in the role setting.
     *
     * @param opps A list of opportunities to be calculated.
     */
    public void calculateOpps(List<Opportunity> opps) {
        for (Opportunity opp: opps) {
            opp.Max_Discount__c = roleSetting.Max_Discount__c;
        }
    }
}